### ISSUE TITLE
Following a team does not seem to be doing anything

### ISSUE THREAD

**Issue by oscherler** [forem/forem#1958]
**Describe the bug**

There seems to be a concept of Teams on dev.to, where posts are written by a member of the team, but are listed under the team name. But the Follow button on such posts does not seem to do anything,

**To Reproduce**

1. Go to 'https://dev.to/vuevixens/hands-on-vuejs-for-beginners-part-6-5e7l';

    The author is Marina Mosti (marinamosti), but the post is filed under a Vue Vixens header, and the Follow button is for Vue Vixens (vuevixens):

![screenshot 2019-03-04 at 10 57 22](https://user-images.githubusercontent.com/189712/53725547-84634880-3e6c-11e9-8896-05a918368f3b.png)

2. Click on 'Follow';
3. Go to 'https://dev.to/dashboard/following';
4. You are following neither Vue Vixens, nor Marina Mosti;
5. Wait for Marina Mosti to publish a new awesome post;
6. You are not being notified of the post.

**Expected behavior**

1. Vue Vixens appears somewhere on your Following page;
2. You are notified whenever any member of the Vue Vixens team publishes a new post.

Unless I misunderstood the whole team thing, that is. ;-)

**Desktop (please complete the following information):**

- OS: Mac OS 10.14
- Browser Safari 12

**Comment by Zhao-Andy** [comment]
If you are following either the organization or the author of the post, you should be receiving a notification when either a member of the org or author publishes a new post. If that's not the case though it's a bug and we can take a look into it. :)

**Comment by Glennmen** [comment]
@Zhao-Andy Now that I think about it I also don't think I have ever received a notification from the dev.to staff and I have been following them for at least a couple weeks. For example no notification for the "Welcome Thread" published yesterday.

I am also following The DEV Team but for some reason it isn't shown in my Followed Users list 🤔

**Comment by dabrorius** [comment]
Hi everyone,
this issue might be more of a missing feature? I just followed "Evil Martians" (in production app) and noticed that I can't see that I'm following them in my dashboard (https://dev.to/dashboard/following). They don't appear under tags, nor the users list. Should there be a third "teams" list there?

**Comment by Zhao-Andy** [comment]
@dabrorius yeah I'd agree with that. We currently don't show any organizations in the "FOLLOWING" dashboard as you mentioned. It might make sense to have a third tab, or maybe an option to filter by type.

@Glennmen sorry just seeing you message now. The "Welcome Thread" is actually posted by the `user` "dev.to staff" and not under the organization. So to receive the notification, you'd have to be following that specific `user`. That's sort of legacy stuff that we haven't discussed as a team, and it would probably make sense to post those under the organization.

**Comment by dabrorius** [comment]
@Zhao-Andy I might give this a shot, I've started working on it locally. Seems pretty straightforward but I'm still missing tests, this is how it looks like currently:

<img width="1274" alt="Screen Shot 2019-03-20 at 15 53 47" src="https://user-images.githubusercontent.com/690113/54694418-80038480-4b28-11e9-9a53-29c8c148fafc.png">

**Comment by Zhao-Andy** [comment]
That looks great! I think it makes sense to have to below tags and users. I'd recommend watching out for any `n+1` queries.

**Comment by dabrorius** [comment]
@Zhao-Andy thanks for the tip, will do! I won't promise anything but I'll try to get a PR ready this week.

**Comment by maestromac** [comment]
Resolved with #2157

**Comment by dabrorius** [comment]
@maestromac please note that I did not test anything regarding notifications from followed organizations. My PR resolves a part of this issue, but deeper issues regarding notifications might still exist.

**Comment by maestromac** [comment]
Oh good point. Reopen for the notification portion.

**Comment by jessleenyc** [comment]
I'm pretty sure I've been receiving notifications from orgs that I follow. Is this still an issue for you @oscherler?

**Comment by Link2Twenty** [comment]
@jessleenyc I've been receiving notifications from orgs too, I'd say this is sorted.

**Comment by rhymes** [comment]
Closing this as we clearly receive notifications from organizations
