### ISSUE TITLE
Article show page: broken timestamp

### ISSUE THREAD

**Issue by mzakzook** [forem/forem#7086]
**Describe the bug**

The date printed to my post is one day ahead. Hover-over shows correct date.

<img width="1094" alt="Screen Shot 2020-03-28 at 10 06 09 AM" src="https://user-images.githubusercontent.com/19253610/78457486-5b107f80-765f-11ea-9287-e888552291dd.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="1094" alt="Screen Shot 2020-03-28 at 10 06 09 AM" src="https://user-images.githubusercontent.com/19253610/78457497-711e4000-765f-11ea-95c5-55f60845d056.png">

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

My timezone is Pacific Time.

**Comment by citizen428** [comment]
Thanks for the issue @mzakzook! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
For anyone investigating this: if I had to venture a guess, I'd say we store this in UTC without time zone info, so when a post is written at specific times of the day (anything from midnight - UTC offset to midnight) this happens. This may be wrong though, as it's just a gut feeling based on previous experiences.

**Comment by rhymes** [comment]
This happens because the datetime in the HTML `title` attribute is correctly rendered using the client's computer timezone, while `Mar 23`, the one shown in the text, is computed server side and the server is always in UTC. 

Great catch @mzakzook and good instincts @citizen428 :D

**Comment by rhymes** [comment]
I played with it a bit and it's definitely doable, we already have the function to do it. There are a few decisions to be made:

- do we want to localize the visible string? Right now we're only localizing `title` attributes, both for articles and for comments:

https://github.com/thepracticaldev/dev.to/blob/b1ebc32e454bd3fe70abf76edcb83b2ec74594ac/app/assets/javascripts/initializers/initializeArticleDate.js#L7-L11

https://github.com/thepracticaldev/dev.to/blob/b1ebc32e454bd3fe70abf76edcb83b2ec74594ac/app/assets/javascripts/initializers/initializeCommentDate.js#L7-L9

- if so, what should be the format? Right now we display `Apr 1` for dates in the current year and `Apr 1 '19` for dates in past years:

https://github.com/thepracticaldev/dev.to/blob/b1ebc32e454bd3fe70abf76edcb83b2ec74594ac/app/models/article.rb#L362-L367

https://github.com/thepracticaldev/dev.to/blob/b1ebc32e454bd3fe70abf76edcb83b2ec74594ac/app/models/comment.rb#L107-L111

**Comment by corentinbettiol** [comment]
Storing all dates in UTC is definitely a good think.

I think we should localize dates in articles & comments (titles attributes *and* datetime tags), and execute `addLocalizedDateTimeToElementsTitles` on them.

Then, if the datetime is in a title, we should keep the long string, and else keep the `%b %e` (or `%b %e '%y`).

----

We can see [here](https://github.com/thepracticaldev/dev.to/blob/773982e210ae0ee74189da3e51e8aedd7479bdfb/app/assets/javascripts/utilities/localDateTime.js#L28-L59) that we only set the title attribute, but we don't update the content of `element`:

https://github.com/thepracticaldev/dev.to/blob/773982e210ae0ee74189da3e51e8aedd7479bdfb/app/assets/javascripts/utilities/localDateTime.js#L56

We can also see how localDateTime is defined here: 
https://github.com/thepracticaldev/dev.to/blob/773982e210ae0ee74189da3e51e8aedd7479bdfb/app/assets/javascripts/utilities/localDateTime.js#L21-L22

*(So localDateTime is just a local translated string obtained from a `Date()` object)*
![image](https://user-images.githubusercontent.com/45763865/80481898-99921500-8953-11ea-9659-e5a7eb7e6fa6.png)

----

We can add something like `element.innerHTML = localDateTime` in `localDateTime.js`, next to the line 56 (`element.setAttribute('title', localDateTime);`)?

*(I don't know if we should use `innerHTML` since [it could lead to a XSS](https://stackoverflow.com/a/25273968/6813732) if localDateTime is a user-defined content)*

**Comment by rhymes** [comment]
> We can see here that we only set the title attribute, but we don't update the content of element

Yeah, initially it was done like that because we didn't want for users to see date time text in different locales, as 99% of the website isn't localized. Don't know if we want to start changing that. I'll raise the issue internally.

**Comment by corentinbettiol** [comment]
@rhymes Oh, I didn't know that the website isn't localized :o

So maybe we could set "*Local time: `%b %e`*" in the title as a temporary fix ?

**Comment by pashagray** [comment]
I think issue can be closed, problem has been solved. Details: #9269

**Comment by rhymes** [comment]
@pashagray not sure it's the same issue though, #9269 is about the profile page, this is about the difference between the shown date in the article show page and its HTML title attribute

**Comment by nickytonline** [comment]
@eclectic-coding and I will be pairing on this today. https://twitter.com/nickytonline/status/1287802825544732678

**Comment by eclectic-coding** [comment]
Looking forward to working through this with you @nickytonline

**Comment by eclectic-coding** [comment]
After reviewing this issue with @nickytonline we were unable to replicate. It is probable that the #9285 new `local_date` helper has resolved this issue. Please review and verify before this open issue is closed. If not, and it is still an issue, I will be glad to look at it again. 
Thank you for the opportunity.

**Comment by mzakzook** [comment]
Quick check looks good on the article show page. I did notice that dates printed next to each post title on the User show page are not consistent with article show page (correct date is on article show). Photos attached.
![C7C85CA8-3304-431C-9B2C-1264F74CB66A](https://user-images.githubusercontent.com/19253610/88736367-824afb00-d0ed-11ea-9226-817c51d7a15b.png)
![46A9A6BB-7DC7-4EE1-AE7A-9FD439CCFE65](https://user-images.githubusercontent.com/19253610/88736418-85de8200-d0ed-11ea-9616-28447514fa93.png)
