### ISSUE TITLE
Article view counters in dashboard are not updating

### ISSUE THREAD

**Issue by EwertonJordao** [forem/forem#8425]
**Describe the bug**
Hi everyone

I had some problem with my counter viewers on my posts, it's freeze in 1085 viewers, but I receive interactions with my post, and the number of viewers won't be updated, can check what's happening for not update data?

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 1909
- Browser: Firefox Developer
- Version: 78.0b5

**Comment by citizen428** [comment]
Can you please provide a link to the post where this is happening?

**Comment by EwertonJordao** [comment]
For all posts, I receive some tags and reactions on my content but counter it's freeze. I the past when I publish an article they stop counter in 205 viewers and one month after I saw 500 viewers I think the difference is not reflecting access the one day it's impossible. In the dashboard, we access estimate of access but if I use API I can see the exact number of viewers. the data is not collected gradually and increments the dashboard in real-time.
For example this post https://dev.to/ewertonjordao/utilizando-azure-functions-powershell-core-kafkatrigger-1gd https://dev.to/ewertonjordao/winget-o-gerenciador-de-pacotes-windows-10-4m3l

I receive this reaction yesterday:
![image](https://user-images.githubusercontent.com/12378570/84478513-d39b4a00-ac67-11ea-89c9-28cf968e7af6.png)

And the count still in 1085 viewers

Thanks.

**Comment by mrshawnhum** [comment]
I believe my view count has been frozen as well. I had 33 views with the first 5-15 minutes of the article being published, but then I received no more views and would still receive interactions.

https://dev.to/mrshawnhum/your-background-doesn-t-matter-4ad0

**Comment by EwertonJordao** [comment]
I think they doing more things for UX, but in basic functionalities, nobody cares 🤷‍♂️.

**Comment by mrshawnhum** [comment]
> I think they doing more things for UX, but in basic functionalities, nobody cares 🤷‍♂️.

Someone that is trying to see how they can improve on their articles care, but that's good if they have been doing more for UX.

**Comment by citizen428** [comment]
> I think they doing more things for UX, but in basic functionalities, nobody cares 🤷‍♂️.

Of course we care, but we also just organized a conference (CodeLand:Distributed) and put a lot of work into generalizing the codebase for other communities. Note that this PR is tagged as a bug and therefore is open for contributions by everyone, not just core team members.

**Comment by EwertonJordao** [comment]
Okay, I was unfair. However, for those who produce technical content, this is extremely important to understand what people liked to read and serve as a basis for the next posts. I think the flag should be made explicit with priority level a bug is just another bug.

**Comment by EwertonJordao** [comment]
I really since the counter freeze, I am studying to go back to another platform 🤦‍♂️🤷‍♂️

**Comment by pathiknd** [comment]
Same for me too. My view counter has been frozen for 40-45 days. I have published new content and it has been viewed. Earlier also the view counter updated randomly. Someday it would update and then would stop for few days and then suddenly you would see updated count, but it has not changed for at least 40-45 days for me.

**Comment by rhymes** [comment]
Hi @EwertonJordao, @mrshawnhum, @pathiknd I started looking into this and I'd like to confirm with you some data to better understand what's going on, though I'm starting to have my suspicions.

Let's start from the beginning, not page views tracked are displayed. We do sample them:

https://github.com/forem/forem/blob/dbbe158d21caabfffa2c7c5c56ebc2e615fc9fda/app/controllers/page_views_controller.rb#L35

At the present moment, August 6th our DB has the following `page_views_count` for the following articles (I used the three @EwertonJordao and @mrshawnhum linked):


username | path | title | page_views_count
-- | -- | -- | --
mrshawnhum | /mrshawnhum/your-background-doesn-t-matter-4ad0 | YOUR BACKGROUND DOESN'T MATTER | 33
ewertonjordao | /ewertonjordao/utilizando-azure-functions-powershell-core-kafkatrigger-1gd | Utilizando Azure Functions (PowerShell Core) KafkaTrigger | 10
ewertonjordao | /ewertonjordao/winget-o-gerenciador-de-pacotes-windows-10-4m3l | WinGet o gerenciador de pacotes Windows 10 | 40

So this is what you should see in your https://dev.to/dashboard in the icon for page views. For example, from one of my articles:

![Screenshot_2020-08-06 Dashboard - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/89522208-1cdbc600-d7e1-11ea-8a88-d2e04b3aa682.png)

If we observe the logic behind the code:

https://github.com/forem/forem/blob/dbbe158d21caabfffa2c7c5c56ebc2e615fc9fda/app/controllers/page_views_controller.rb#L13-L15

followed by

https://github.com/forem/forem/blob/dbbe158d21caabfffa2c7c5c56ebc2e615fc9fda/app/controllers/page_views_controller.rb#L34-L42

we notice two things (one already mentioned):

- the page view is counted each time
- the page view cached count is only updated once a while depending on the randomizer

To confirm that I went ahead and pulled the data from our `page_views` table using these 3 articles and found the following data:


path | sum
-- | --
/ewertonjordao/utilizando-azure-functions-powershell-core-kafkatrigger-1gd | 37
/ewertonjordao/winget-o-gerenciador-de-pacotes-windows-10-4m3l | 138
/mrshawnhum/your-background-doesn-t-matter-4ad0 | 105

It's clear that there's a discrepancy between the displayed counter and the actual data we have that counts the page views.

- `/ewertonjordao/utilizando-azure-functions-powershell-core-kafkatrigger-1gd` shows 10 views but we have 37 registered
- `/ewertonjordao/winget-o-gerenciador-de-pacotes-windows-10-4m3l` shows 40 views but we have 138
- `/mrshawnhum/your-background-doesn-t-matter-4ad0` shows 33 views but we have 105

These are my findings as of now. I'll keep investigating to find a proper solution.

**Comment by EwertonJordao** [comment]
Thanks for this. But why we have a delay to see this data? I use Rest Api of dev.to and page count is the same as the dashboard, so where's data and how you collected this? we can read this too?

**Comment by vishnuchilamakuru** [comment]
I am also facing this issue currently. Ex: https://dev.to/vishnuchilamakuru/managing-self-balancing-performance-vs-stress-51nb this blog views counter stopped at 99 views whereas I still get notifications for reactions on the blog post. Not sure how frequently does the blog views gets updated is it hourly or daily ?

**Comment by Pobb** [comment]
What is the "cache" strategy behind this value ? I know that "cache" will improve performance, but can we get info about time execution of this request ? Even if we don't need real time for this value, we need the "correct" value. In case of strategy maybe we can look to another way (async ? update cache less randomly ? etc.) 

Random here is not working, I made a script that curl 100 times on my dashboard, nothing append (FYI).

**Comment by Pobb** [comment]
I got a "new" problem with this feature : I got 3 articles on my dashboard from a long time now. I share one of the three on social network, just one of them.

My dashboard was updated today, but the wrong articles get "50" more clics. It's not possible at all. Have you got an idea about this feature @rhymes ?

**Comment by krzysiek1507** [comment]
The short term solution might be to revert this change: https://github.com/forem/forem/pull/4945/files#diff-d9859d2253c6f3c197db32eb2baad2b331b5f75a576ca0e7e6038e25b1ed32e5L33 (just this one line). Probably it was done for the performance reasons but I don't know the stats.

The long term solution might be storing article id in Redis in a re-count queue and re-count every few minutes/hours in the background.

**Comment by krzysiek1507** [comment]
I submitted a PR #11286 that reverts `rand` max value to the previous value.

**Comment by mstruve** [comment]
Let's figure out a solution to this that helps us continue to maintain performance while also making sure the author is adequately up to date on their page views. One suggestion would be when an author visits their own post we ALWAYS update the counter or something along those lines to ensure the author is always seeing the correct number even if others are delayed.

**Comment by fdoxyz** [comment]
Based on something similar I did in another PR I wanted to suggested a solution for this:

1. Extract the `update_article_page_views` logic into a Background worker (i.e. `UpdateArticlePageViewsWorker`)
2. Make sure we schedule the worker in the future (from `page_views#create`) with `UpdateArticlePageViewsWorker.perform_at(30.minutes.from_now)`
3. Ensure [the worker is unique in the queue](https://github.com/mhenrixon/sidekiq-unique-jobs) so the performance won't be heavily impacted. An example config to make this work:

```ruby
class UpdateArticlePageViewsWorker
    include Sidekiq::Worker

    sidekiq_options queue: :medium_priority,
                    retry: 10,
                    lock: :until_executed,
                    on_conflict: :replace

...

end
```

## Implications of this implementation

1. Articles that get traffic bursts in short periods (i.e. shared on social) won't negatively impact performance. This would likely make this more performant instead:
   - This strategy would update the stats **at most** every X minutes (configurable but the example above uses 30 min intervals) even if the Article gets 1,000 views in 2h
   - With the current implementation we would get 1/8 chance of updating the counters **on every page view**. With the same example of 1,000 views in 2h this would result in 125 updates (1,000 * 12.5%)
2. Every Page View will be accounted for
   - In the current implementation they will only be accounted for if they meet the chance of 1/8. For context, the probability of an Article getting 6 Page Views and **not updating** is 44.87%
   - With the suggested solution every Page View will either schedule a job to update the counters or a job to update is already scheduled so no action in necessary


Open to thoughts/feedback/alternatives on this proposal :)

**Comment by mstruve** [comment]
Interesting, I love the idea of not kicking off the worker right away but scheduling it for the future with a unique constraint. I would even dial in the time to 1-5 mins in the future to run the job to keep it more up to date.

**Comment by citizen428** [comment]
I know we're nowhere near Reddit-scale, but their approach is also quite interesting: they use secondary storage like Redis to provide more accurate counts for the users themselves while utilizing background jobs to update the stored number in the main data store. This approach would obviously be quite heavy on Redis (1 key per article, though we could have an expiry on keys so this stays at a manageable size) and we'd immediately `INCR` the count there while scheduling background jobs.
